service: uport-email-verification

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  environment:
    PORT: 5000
    APP_NAME: ""
    ADDRESS: ""
    PRIVATE_KEY: ""
    EMAIL_USER: ""
    EMAIL_PASS: ""

functions:
  app:
    handler: server.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'